### ISSUE TITLE
ValueError when comparing loss values

### ISSUE THREAD

**Issue by HarshSharma12** [maksym33/FeatureImportanceDL#2]
I was trying with a custom dataset and I'm getting the following error

>   File "test_custom.py", line 127, in <module>
>     fs.train_networks_on_data(Xtrain, ytrain, max_batches, val_data=(Xval, yval))
>   File "FeatureImportanceDL/src/FeatureSelector.py", line 118, in train_networks_on_data
>     gen_new_opt_mask=selector_train_condition)
>   File "FeatureImportanceDL/src/MaskOptimizer.py", line 162, in get_new_mask_batch
>     self.mask_opt = self.get_opt_mask(self.unmasked_data_size, model)
>   File "FeatureImportanceDL/src/MaskOptimizer.py", line 118, in get_opt_mask
>     max_index, m_opt_grad)
>   File "FeatureImportanceDL/src/MaskOptimizer.py", line 78, in new_check_for_likely_change
>     if (m_new_opt_loss < m_opt_loss):
> ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Should this be .any() or .all()?

**Comment by HarshSharma12** [comment]
I got it working with  **if (m_new_opt_loss < m_opt_loss).all()** which seems to be the correct as per the paper. Leaving this open so that it can be fixed (and in case I'm wrong).

**Comment by maksym33** [comment]
Hello,
Thank you for raising this issue.
I am not sure how this happened, as both of the compared losses should be scalars, not arrays, unless you are using a custom loss.
Can you show me an example from your code?

**Comment by HarshSharma12** [comment]
Hey,
The only changes I did were data related and in the example file. I have added snippets below (other things like model, batch size etc. remain the same)

1. Read data from a csv
```
df_full = pd.read_csv('data.csv', index_col=0)
df_full = df_full.reset_index(drop=True)

all_X = df_full.drop(target, axis=1)
all_y = df_full[target]
```
2. Split into train/test/val
```
Xtrain, Xtest, ytrain, ytest = train_test_split(
    all_X,
    all_y,
    test_size = 0.25,
    random_state = 42
)


Xtrain, Xval, ytrain, yval = train_test_split(
    Xtrain,
    ytrain,
    test_size = 0.25,
    random_state = 69
)
```
3. Convert to NumPy
```
ytrain = get_one_hot(ytrain.astype(np.int8), 4)
ytest = get_one_hot(ytest.astype(np.int8), 4)
yval = get_one_hot(yval.astype(np.int8), 4)


Xtrain = Xtrain.to_numpy()
Xval = Xval.to_numpy()
Xtest = Xtest.to_numpy()
```

**Comment by maksym33** [comment]
Unfortunately, I cannot reproduce that error: maybe you can send me a few samples of your data?
You can also check what are the shapes of the  `new_m_opt_loss` and `m_opt_loss`, maybe that will give us a clue.
The losses should be scalars: 1 loss for **m_opt** and another one for **new_m_opt**, so I will have a look and see what is wrong.

**Comment by HarshSharma12** [comment]
Unfortunately, I can't share the data. I created a custom CSV similar to the original data but was not able to replicate the issue. 

I'm closing this, as now it seems like a one off case. I'll add more details if I'm able to figure out what's happening. 


Thanks a lot for the help and for making the code accessible. Great work on the paper and the method.
